name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull requests to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Set up Docker to build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Google Cloud
      - name: Google Cloud Login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 6: Configure GCP Project
      - name: Set up Google Cloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region us-central1
          gcloud config set compute/zone us-central1-a

      # Step 7: Build and push Docker image to GCR
      - name: Build and push Docker image to GCR
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-gcp-app:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-gcp-app:latest

      # Step 8: Install Pulumi
      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin
          pulumi version

      # Step 9: Set up Pulumi configuration (credentials)
      - name: Set Pulumi config
        run: |
          pulumi config set gcp:project ${{ secrets.GCP_PROJECT_ID }}
          pulumi config set gcp:region us-central1
          pulumi config set redis:instance_ip ${{ secrets.REDIS_IP }}  # If using Redis (otherwise remove this line)
          pulumi config set google:credentials ${{ secrets.GCP_CREDENTIALS }}

      # Step 10: Run Pulumi to deploy to Google Cloud Run
      - name: Run Pulumi to deploy
        run: |
          pulumi stack select dev  # Select your Pulumi stack
          pulumi up --yes  # Run Pulumi to deploy without confirmation

      # Step 11: Output the URL of the deployed service
      - name: Output deployed URL
        run: |
          echo "Deployed service URL: $(pulumi stack output url)"
