name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      
      - name: Checkout repository
        uses: actions/checkout@v3

    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

   
      - name: Install dependencies
        run: |
          npm install

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

     
      - name: Google Cloud Login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region us-central1
          gcloud config set compute/zone us-central1-a

     
      - name: Build and push Docker image to GCR
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-gcp-app:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-gcp-app:latest

      
      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin
          pulumi version

     
      - name: Set Pulumi config
        run: |
          pulumi config set gcp:project ${{ secrets.GCP_PROJECT_ID }}
          pulumi config set gcp:region us-central1
          pulumi config set redis:instance_ip ${{ secrets.REDIS_IP }}  # If using Redis (otherwise remove this line)
          pulumi config set google:credentials ${{ secrets.GCP_CREDENTIALS }}

      
      - name: Run Pulumi to deploy
        run: |
          pulumi stack select dev  # Select your Pulumi stack
          pulumi up --yes  # Run Pulumi to deploy without confirmation

      
      - name: Output deployed URL
        run: |
          echo "Deployed service URL: $(pulumi stack output url)"
